### ISSUE TITLE
Hard AI does not recruit pikemen in villages

### ISSUE THREAD

**Issue by sumpfralle** [triplea-maps/house_of_habsburg#2]
The hard AI does not seem to recruit pikemen from villages.

This is a heavy burden especially for Russia, since it has only one city and thus accumulates its PUs without any use, even though there are plenty of villages to be used for spending PUs.

(see the savegame from #1 for an example)

I do not know, whether this is an issue for other AIs, as well.

**Comment by CharlieAtlas** [comment]
I am pretty sure that the AI doesn't buy anything that consumes other units.  If it does, it is an accident.

**Comment by sumpfralle** [comment]
What a pity!
